apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgresql-12-custom
  name: postgresql-12-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-12-custom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql-12-custom
    spec:
      containers:
      - image: quay.io/tdahlen/postgresql-12-custom:v1.0
        name: postgresql-12-custom
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: db
        - name: POSTGRESQL_PASSWORD
          value: secret
        - name: POSTGRESQL_DATABASE
          value: rpi-store
        resources: {}
status: {}
